Repository boostcampwm-2022/web03-FanUP, pull requests merged in 2022-12, with the labels that each got.

#87 Feat: Ticket Service Template
  .github/workflows/CLIENT-DEPLOY.yml
  client/package.json
  client/src/App.tsx
  client/src/components/UI/molecules/calendarBody/index.tsx
  client/src/components/UI/molecules/scheduleFanUpModal/constants.ts
  client/src/components/UI/molecules/scheduleFanUpModal/index.tsx
  client/src/components/UI/organisms/allTickets/index.tsx
  client/src/components/UI/organisms/calendar/index.tsx
  client/src/components/UI/organisms/detailTicket/index.tsx
  client/src/components/UI/organisms/todayTickets/index.tsx
  client/src/components/hoc/modal/index.tsx
  client/src/hooks/useTimer.ts
  client/src/pages/Home/index.tsx
  client/src/services/ticket.ts
  client/src/types/ticket.d.ts
  client/src/utils/serverUrl.ts
Labels: 🎨 프론트엔드, ✨ Feature

#110 Hotfix/#109 WebRTC 연결, 해제 로직 수정
  client/package.json
  client/public/favicon.ico
  client/public/favicon.svg
  client/public/index.html
  client/src/components/UI/atoms/defaultImg/index.tsx
  client/src/components/UI/organisms/ChatContainer/index.tsx
  client/src/components/icons/SubLogo.tsx
  client/src/hooks/useFanUP.ts
  client/src/pages/FanUP/index.tsx
  client/src/pages/Home/index.tsx
  client/src/socket.ts
  server/gateway/src/api/core/core.controller.ts
  server/gateway/src/socket/fanup/fanup.service.ts
Labels: 🐞 Hotfix, 🎨 프론트엔드, ⚡ 백엔드

#111 Fix/#101 oauth login
  server/gateway/package-lock.json
  server/gateway/package.json
  server/gateway/src/api/auth/auth.controller.ts
  server/gateway/src/api/auth/auth.guard.ts
  server/gateway/src/api/auth/auth.module.ts
  server/gateway/src/api/auth/auth.service.ts
  server/gateway/src/api/auth/dto/login.dto.ts
  server/gateway/src/api/auth/strategies/jwt.strategy.ts
  server/services/auth/package-lock.json
  server/services/auth/package.json
  server/services/auth/prisma/schema.prisma
  server/services/auth/src/auth/auth.controller.ts
  server/services/auth/src/auth/auth.module.ts
  server/services/auth/src/auth/auth.service.ts
  server/services/auth/src/auth/dto/request-login.dto.ts
  server/services/auth/src/auth/jwt.service.ts
  server/services/auth/src/auth/strategy/jwt.strategy.ts
  server/services/auth/src/auth/strategy/refresh.strategy.ts
  server/services/auth/src/common/constants/index.ts
  server/services/auth/src/common/constants/res-message.ts
  server/services/auth/src/common/constants/res-status-code.ts
  server/services/auth/src/common/exception/filter/http-exception.filter.ts
  server/services/auth/src/common/exception/rpc/login-fail.exception.ts
  server/services/auth/src/common/strategies/google.strategy.ts
  server/services/auth/src/common/strategies/jwt.strategy.ts
  server/services/auth/src/common/strategies/kakao.strategy.ts
  server/services/auth/src/main.ts
  server/services/auth/src/user/user.service.ts
  server/services/ticket/package.json
Labels: ⚡ 백엔드, ✨ Feature

#115 Feat/#114 Logout
  client/src/components/UI/atoms/ExitBtn/index.tsx
  client/src/components/UI/atoms/LogOutBtn/index.tsx
  client/src/components/UI/organisms/header/index.tsx
  client/src/components/icons/ExitIcon.tsx
  client/src/services/user.service.ts
  client/src/store/user/index.ts
Labels: 🎨 프론트엔드, ✨ Feature

#121 Feat/#120 Schedule Page, Nickname Edit Modal
  client/src/App.tsx
  client/src/Routes.ts
  client/src/components/UI/atoms/ExitBtn/index.tsx
  client/src/components/UI/molecules/NicknameEditModal/index.tsx
  client/src/components/UI/molecules/calendarHeader/index.tsx
  client/src/components/UI/molecules/calendarHeader/test/index.test.tsx
  client/src/components/UI/molecules/scheduleFanUpModal/index.tsx
  client/src/components/UI/organisms/MyFeatureBox/index.tsx
  client/src/components/UI/organisms/MyFeatureBox/test/index.test.tsx
  client/src/components/UI/organisms/VideoList/index.tsx
  client/src/components/UI/organisms/calendar/index.tsx
  client/src/components/UI/organisms/header/index.tsx
  client/src/hooks/useCheckLogin.ts
  client/src/hooks/useModal.ts
  client/src/pages/Home/index.tsx
  client/src/pages/Schedule/index.tsx
  client/src/pages/Tickets/index.tsx
  client/src/utils/addZero.ts
Labels: 🎨 프론트엔드, ✨ Feature

#123 Fix/#122 global exception handler
  server/gateway/src/api/auth/auth.controller.ts
  server/gateway/src/common/exception/custom-rpc-exception.d.ts
  server/gateway/src/common/exception/filter/global-exception.filter.ts
  server/services/auth/src/app.module.ts
  server/services/auth/src/common/exception/custom-rpc-exception.d.ts
  server/services/auth/src/common/exception/custom-rpc-exception.ts
  server/services/auth/src/common/exception/custom-rpc.exception.ts
  server/services/auth/src/common/exception/filter/custom-rpc-exception.filter.ts
  server/services/auth/src/common/exception/filter/http-exception.filter.ts
  server/services/auth/src/common/exception/filter/rpc-exception.filter.ts
  server/services/auth/src/domain/auth/auth.controller.ts
  server/services/auth/src/domain/auth/auth.module.ts
  server/services/auth/src/domain/auth/auth.service.ts
  server/services/auth/src/domain/auth/dto/request-login.dto.ts
  server/services/auth/src/domain/auth/jwt.service.ts
  server/services/auth/src/domain/auth/strategy/jwt.strategy.ts
  server/services/auth/src/domain/auth/strategy/refresh.strategy.ts
  server/services/auth/src/domain/user/dto/user.dto.ts
  server/services/auth/src/domain/user/user.module.ts
  server/services/auth/src/domain/user/user.service.ts
  server/services/auth/src/main.ts
Labels: enhancement, ⚡ 백엔드

#127 Feat/#126 Regist Artist
  client/src/App.tsx
  client/src/Routes.ts
  client/src/components/UI/molecules/NicknameEditModal/index.tsx
  client/src/components/UI/molecules/SubscribedUser/index.tsx
  client/src/components/UI/organisms/ArtistInfoForm/index.tsx
  client/src/components/UI/organisms/OAuthContainer/index.tsx
  client/src/components/UI/organisms/SubscribedUsers/index.tsx
  client/src/components/UI/organisms/calendar/index.tsx
  client/src/components/UI/organisms/header/index.tsx
  client/src/components/icons/PlusIcon.tsx
  client/src/hooks/useCheckArtist.ts
  client/src/hooks/useInput.ts
  client/src/hooks/useLogin.ts
  client/src/pages/Artist/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Schedule/index.tsx
  client/src/services/artist.service.ts
  client/src/services/file.service.ts
  client/src/store/index.ts
  client/src/store/rootReducer.ts
  client/src/style/styled.d.ts
  client/src/style/theme.ts
Labels: 🎨 프론트엔드, ✨ Feature

#129 Feat/#128 ErrorBoundary 도입
  client/src/App.tsx
  client/src/components/hoc/errorBoundary/index.tsx
  client/src/components/icons/ErrorIcon.tsx
  client/src/pages/404/index.tsx
Labels: 🎨 프론트엔드, ✨ Feature

#124 Feat/#93 artist logic
  server/gateway/src/api/auth/auth.controller.ts
  server/gateway/src/api/auth/auth.service.ts
  server/gateway/src/api/auth/dto/create-artist.dto.ts
  server/gateway/src/api/auth/dto/login.dto.ts
  server/gateway/src/api/auth/strategies/jwt.strategy.ts
  server/gateway/src/common/exception/custom-rpc-exception.d.ts
  server/gateway/src/common/exception/filter/global-exception.filter.ts
  server/services/auth/prisma/schema.prisma
  server/services/auth/src/app.module.ts
  server/services/auth/src/domain/artist/artist.controller.ts
  server/services/auth/src/domain/artist/artist.module.ts
  server/services/auth/src/domain/artist/artist.service.ts
  server/services/auth/src/domain/artist/dto/reqeust-create-artist.dto.ts
  server/services/auth/src/domain/auth/auth.controller.ts
  server/services/auth/src/domain/auth/auth.service.ts
  server/services/auth/src/domain/favorite/dto/favorite.dto.ts
  server/services/auth/src/domain/favorite/favorite.controller.ts
  server/services/auth/src/domain/favorite/favorite.module.ts
  server/services/auth/src/domain/favorite/favorite.service.ts
  server/services/auth/src/domain/user/dto/request-create-user.dto.ts
  server/services/auth/src/domain/user/dto/user.dto.ts
  server/services/auth/src/domain/user/user.service.ts
Labels: ⚡ 백엔드, ✨ Feature

#131 Feat/#130 notification improve
  server/services/core/src/common/constants/microservices.ts
  server/services/core/src/common/type/index.ts
  server/services/core/src/common/type/ticket.d.ts
  server/services/core/src/common/util/date.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/core/src/job/job.module.ts
  server/services/core/src/job/job.service.ts
  server/services/core/src/job/task/basic.task.ts
  server/services/core/src/job/task/fanup-notification.task.ts
  server/services/ticket/src/common/util/date.ts
  server/services/ticket/src/domain/ticket/ticket.controller.ts
  server/services/ticket/src/domain/ticket/ticket.service.ts
  server/services/ticket/src/domain/user-ticket/user-ticket.controller.ts
  server/services/ticket/src/domain/user-ticket/user-ticket.service.ts
Labels: ⚡ 백엔드, ✨ Feature

#134 Feat/#133 아티스트 등록, 아티스트 목록 조회, 구독
  client/src/components/UI/atoms/LogOutBtn/index.tsx
  client/src/components/UI/atoms/NoArtists/index.tsx
  client/src/components/UI/atoms/SubscribeBtn/index.tsx
  client/src/components/UI/atoms/defaultImg/index.tsx
  client/src/components/UI/molecules/artistCard/index.tsx
  client/src/components/UI/molecules/artistCard/test/index.test.tsx
  client/src/components/UI/molecules/artistListViewModeSelector/index.tsx
  client/src/components/UI/organisms/ArtistInfoForm/index.tsx
  client/src/components/UI/organisms/artists/index.tsx
  client/src/components/UI/organisms/artists/test/index.test.tsx
  client/src/components/UI/organisms/artistsBox/index.tsx
  client/src/components/icons/heart.tsx
  client/src/components/icons/unheart.tsx
  client/src/hooks/useDebounce.ts
  client/src/hooks/useOptimisticUI.ts
  client/src/pages/Artist/index.tsx
  client/src/services/artist.service.ts
  client/src/services/user.service.ts
  client/src/store/user/index.ts
  client/src/types/artist.d.ts
  client/src/utils/dummy.ts
Labels: 🎨 프론트엔드, ✨ Feature

#138 Feat/ Sentry도입
  client/package.json
  client/public/dropDown.jpg
  client/src/App.tsx
  client/src/components/UI/atoms/LogOutBtn/index.tsx
  client/src/components/UI/atoms/SubscribeBtn/index.tsx
  client/src/components/UI/molecules/HeaderUser/index.tsx
  client/src/components/UI/molecules/NicknameEditModal/index.tsx
  client/src/components/UI/molecules/SubscribedUser/index.tsx
  client/src/components/UI/molecules/artistListViewModeSelector/index.tsx
  client/src/components/UI/molecules/userDropDown/index.tsx
  client/src/components/UI/organisms/SubscribedUsers/index.tsx
  client/src/components/UI/organisms/artistsBox/index.tsx
  client/src/components/UI/organisms/detailTicket/index.tsx
  client/src/components/UI/organisms/header/index.tsx
  client/src/components/hoc/errorBoundary/index.tsx
  client/src/components/icons/dropDownIcon.tsx
  client/src/hooks/useDropdownAnimation.ts
  client/src/hooks/useToggle.ts
  client/src/index.tsx
  client/src/services/user.service.ts
  client/src/types/ticket.d.ts
  client/src/utils/isLogin.ts
  client/yarn.lock
Labels: 🎨 프론트엔드, ✨ Feature

#140 Feat: user info 조회 시, artist 정보 추가
  server/gateway/src/common/exception/filter/global-exception.filter.ts
  server/services/auth/src/domain/user/user.service.ts
Labels: ⚡ 백엔드, ✨ Feature

#144 Feat: 채팅 데이터 포맷 설정
  client/package-lock.json
  client/src/components/UI/organisms/ChatContainer/index.tsx
  client/src/hooks/useFanUP.ts
  client/yarn.lock
Labels: 리뷰요청, 🎨 프론트엔드

#145 Fix: getArtistList query string
  client/src/components/UI/molecules/artistCard/index.tsx
  client/src/components/UI/molecules/artistCard/test/index.test.tsx
  client/src/components/UI/molecules/artistListViewModeSelector/index.tsx
  client/src/components/UI/organisms/ArtistInfoForm/index.tsx
  client/src/components/UI/organisms/ArtistScheduleBox/index.tsx
  client/src/components/UI/organisms/FanFeatureBox/index.tsx
  client/src/components/UI/organisms/FanFeatureBox/test/index.test.tsx
  client/src/components/UI/organisms/artists/index.tsx
  client/src/components/UI/organisms/artistsBox/index.tsx
  client/src/components/UI/organisms/calendar/index.tsx
  client/src/components/UI/organisms/header/index.tsx
  client/src/components/hoc/errorBoundary/index.tsx
  client/src/hooks/useLogin.ts
  client/src/pages/Home/index.tsx
  client/src/pages/Schedule/index.tsx
  client/src/pages/Tickets/index.tsx
  client/src/services/artist.service.ts
  client/src/services/ticket.service.ts
  client/src/services/user.service.ts
  client/src/types/artist.d.ts
  client/src/types/user.d.ts
  client/src/utils/dummy.ts
Labels: 🎨 프론트엔드, ✨ Feature

#147 Feat/#146 user nickname 수정
  server/gateway/src/api/auth/auth.controller.ts
  server/gateway/src/api/auth/auth.service.ts
  server/gateway/src/api/auth/dto/update-user.dto.ts
  server/services/auth/src/app.module.ts
  server/services/auth/src/domain/auth/auth.module.ts
  server/services/auth/src/domain/user/dto/request-update-user.dto.ts
  server/services/auth/src/domain/user/user.controller.ts
  server/services/auth/src/domain/user/user.module.ts
  server/services/auth/src/domain/user/user.service.ts
Labels: ⚡ 백엔드, ✨ Feature

#149 Feat : 채팅 UI 수정
  client/src/components/UI/atoms/Chat/index.tsx
  client/src/components/UI/molecules/ChatList/index.tsx
  client/src/components/UI/organisms/ChatContainer/index.tsx
Labels: 🎨 프론트엔드

#151 Fix : user-ticket validation 로직 추가
  server/gateway/src/common/types/index.ts
  server/gateway/src/common/types/user-ticket.d.ts
  server/gateway/src/socket/fanup/fanup.service.ts
  server/gateway/src/socket/socket.module.ts
  server/services/core/src/common/constants/res-message.ts
  server/services/core/src/domain/fanup/controller/fanup.controller.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/ticket/src/job/job.listener.ts
Labels: ⚡ 백엔드, ✨ Feature

#150 Fix/#148 Artist list 조회 시, 로그인 여부 상관없이 결과값 받도록 수정
  server/gateway/src/api/auth/auth.controller.ts
  server/services/auth/src/domain/artist/artist.service.ts
Labels: enhancement, ⚡ 백엔드

#152 Feat: schedule fanup validation logic
  client/src/components/UI/atoms/SubscribeBtn/index.tsx
  client/src/components/UI/molecules/HeaderUser/index.tsx
  client/src/components/UI/molecules/NicknameEditModal/index.tsx
  client/src/components/UI/molecules/artistCard/index.tsx
  client/src/components/UI/molecules/calendarBody/index.tsx
  client/src/components/UI/molecules/scheduleFanUpModal/index.tsx
  client/src/components/UI/molecules/userDropDown/index.tsx
  client/src/components/UI/organisms/artists/index.tsx
  client/src/components/UI/organisms/artistsBox/index.tsx
  client/src/components/UI/organisms/calendar/index.tsx
  client/src/components/UI/organisms/header/index.tsx
  client/src/components/hoc/errorBoundary/index.tsx
  client/src/hooks/useFanUP.ts
  client/src/hooks/useLogin.ts
  client/src/index.tsx
  client/src/services/artist.service.ts
  client/src/services/user.service.ts
  client/src/store/user/index.ts
  client/src/types/user.d.ts
  client/src/utils/dateForm.ts
  client/src/utils/isPast.ts
Labels: 🎨 프론트엔드, ✨ Feature

#153 Fix notification error
  server/gateway/src/socket/notification/notification.gateway.ts
  server/services/core/prisma/schema.prisma
  server/services/core/src/common/type/create-ticket.d.ts
  server/services/core/src/common/type/index.ts
  server/services/core/src/domain/fanup/controller/fanup.controller.ts
  server/services/core/src/domain/fanup/dto/create-fanup.dto.ts
  server/services/core/src/domain/fanup/dto/create-time.dto.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/core/src/domain/notification/dto/create-notification.dto.ts
  server/services/core/src/domain/notification/service/notification.service.ts
  server/services/core/src/job/task/fanup-demo.task.ts
  server/services/core/src/job/task/fanup-notification.task.ts
  server/services/ticket/src/domain/ticket/ticket.service.ts
  server/services/ticket/src/job/job.listener.ts
Labels: ⚡ 백엔드, ✨ Feature

#154 Fix/#102 사용자가 구매한 ticket list 조회 기능
  server/gateway/src/api/ticket/ticket.controller.ts
  server/services/ticket/prisma/schema.prisma
  server/services/ticket/src/common/exception/custom-rpc-exception.d.ts
  server/services/ticket/src/common/exception/custom-rpc-exception.ts
  server/services/ticket/src/common/exception/custom-rpc.exception.ts
  server/services/ticket/src/common/exception/filter/custom-rpc-exception.filter.ts
  server/services/ticket/src/common/filter/rpc-exception.filter.ts
  server/services/ticket/src/domain/ticket/ticket.controller.ts
  server/services/ticket/src/domain/ticket/ticket.service.ts
  server/services/ticket/src/domain/user-ticket/user-ticket.controller.ts
  server/services/ticket/src/domain/user-ticket/user-ticket.service.ts
  server/services/ticket/src/main.ts
Labels: enhancement, ⚡ 백엔드

#155 Fix notification error
  server/gateway/src/socket/fanup/fanup.gateway.ts
  server/gateway/src/socket/notification/notification.gateway.ts
  server/gateway/src/socket/notification/notification.service.ts
  server/services/core/src/common/type/create-notification.d.ts
  server/services/core/src/domain/notification/dto/create-notification.dto.ts
  server/services/core/src/job/task/fanup-notification.task.ts
  server/services/ticket/src/job/job.listener.ts
Labels: ⚡ 백엔드, ✨ Feature

#156 Fix notification 읽음 처리
  server/gateway/src/common/types/update-notification.d.ts
  server/gateway/src/socket/notification/notification.gateway.ts
  server/gateway/src/socket/notification/notification.service.ts
  server/services/core/prisma/schema.prisma
  server/services/core/src/domain/fanup/dto/create-fanup.dto.ts
  server/services/core/src/domain/fanup/dto/create-time.dto.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/core/src/domain/notification/controller/notification.controller.ts
  server/services/core/src/domain/notification/service/notification.service.ts
  server/services/core/src/job/task/fanup-notification.task.ts
Labels: ⚡ 백엔드, ✨ Feature

#157 Fix/#102 user ticket history
  server/services/auth/src/common/constants/config.ts
  server/services/auth/src/domain/artist/artist.controller.ts
  server/services/auth/src/domain/artist/artist.module.ts
  server/services/auth/src/domain/artist/artist.service.ts
  server/services/auth/src/main.ts
  server/services/ticket/prisma/schema.prisma
  server/services/ticket/src/app.module.ts
  server/services/ticket/src/domain/artist/artist.controller.ts
  server/services/ticket/src/domain/artist/artist.module.ts
  server/services/ticket/src/domain/artist/artist.service.ts
Labels: enhancement, ⚡ 백엔드

#158 Fix : 유저가 티켓 생성 시 알람 제공
  server/services/ticket/src/job/job.listener.ts
  server/services/ticket/src/job/job.module.ts
Labels: ⚡ 백엔드, ✨ Feature

#162 HotFix/#161 localStorage Clear
  client/src/components/UI/atoms/Button/test/index.test.tsx
  client/src/components/UI/molecules/SmallTicket/index.tsx
  client/src/components/UI/molecules/SmallTicket/test/index.test.tsx
  client/src/components/UI/molecules/artistListViewModeSelector/test/index.test.tsx
  client/src/components/UI/molecules/scheduleFanUpModal/index.tsx
  client/src/components/UI/molecules/userDropDown/index.tsx
  client/src/components/UI/organisms/ArtistScheduleBox/index.tsx
  client/src/components/UI/organisms/FanFeatureBox/index.tsx
  client/src/components/UI/organisms/artistsBox/test/index.test.tsx
  client/src/components/UI/organisms/detailTicket/index.tsx
  client/src/components/UI/organisms/header/test/index.test.tsx
  client/src/components/hoc/errorBoundary/index.tsx
  client/src/pages/Home/index.tsx
  client/src/services/ticket.service.ts
  client/src/services/user.service.ts
  client/src/types/ticket.d.ts
  client/src/utils/initializeLocalStorage.ts
  client/src/utils/isPast.ts
Labels: 🐞 Hotfix, 🎨 프론트엔드

#164 Fix/#163 새로고침 후 로그인 풀림 현상 해결
  client/src/components/UI/molecules/userDropDown/index.tsx
  client/src/components/hoc/errorBoundary/index.tsx
  client/src/services/user.service.ts
  client/src/utils/get_D_Day.ts
Labels: 🐞 Hotfix, 🎨 프론트엔드

#166 Fix 티켓 아이디로 팬미팅방 가져오는 로직 수정
  server/gateway/src/api/core/core.service.ts
  server/services/core/src/domain/fanup/controller/fanup.controller.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/ticket/src/job/job.listener.ts
Labels: 🐞 Hotfix, ⚡ 백엔드

#168 Fix : 버그 수정
  server/gateway/src/socket/fanup/fanup.service.ts
  server/services/ticket/package-lock.json
  server/services/ticket/package.json
  server/services/ticket/src/common/type/fanup.d.ts
  server/services/ticket/src/job/job.listener.ts
Labels: 🐞 Hotfix, ⚡ 백엔드

#169 Feat/#86 팬업 알림 서버 연동
  client/src/components/UI/molecules/NotificationItem/index.tsx
  client/src/components/UI/organisms/ChatContainer/index.tsx
  client/src/components/UI/organisms/NotificationContainer/index.tsx
  client/src/components/UI/organisms/header/index.tsx
  client/src/components/UI/organisms/header/testSocket.ts
Labels: 🎨 프론트엔드

#167 Fix: ticket list 조회 시, artist 정보 추가
  server/gateway/src/api/ticket/ticket.controller.ts
  server/services/auth/src/domain/artist/artist.service.ts
  server/services/core/src/domain/fanup/controller/fanup.controller.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/ticket/src/domain/ticket/dto/request-all-ticket-by-year-and-month.dto.ts
  server/services/ticket/src/domain/ticket/ticket.controller.ts
  server/services/ticket/src/domain/ticket/ticket.module.ts
  server/services/ticket/src/domain/ticket/ticket.service.ts
  server/services/ticket/src/main.ts
Labels: ⚡ 백엔드, ✨ Feature

#170 Fix fanup and notification
  server/gateway/src/socket/notification/notification.gateway.ts
  server/services/ticket/src/job/job.listener.ts
Labels: 🐞 Hotfix, ⚡ 백엔드

#172 Fix 방을 분배하여 알려주는 분배 알고리즘 실행
  server/services/ticket/package-lock.json
  server/services/ticket/package.json
  server/services/ticket/src/domain/user-ticket/user-ticket.service.ts
  server/services/ticket/src/job/job.listener.ts
Labels: 🐞 Hotfix, ⚡ 백엔드

#173 Feat/#171 티켓 아티스트 정보 연결
  client/src/components/UI/atoms/D_Day/index.tsx
  client/src/components/UI/atoms/FeatureModeSelector/index.tsx
  client/src/components/UI/atoms/SubscribeBtn/index.tsx
  client/src/components/UI/atoms/calendarNextBtn/index.tsx
  client/src/components/UI/atoms/calendarPrevBtn/index.tsx
  client/src/components/UI/molecules/HeaderUser/index.tsx
  client/src/components/UI/molecules/NicknameEditModal/index.tsx
  client/src/components/UI/molecules/SmallTicket/index.tsx
  client/src/components/UI/molecules/SmallTicket/test/index.test.tsx
  client/src/components/UI/molecules/allTicket/index.tsx
  client/src/components/UI/molecules/allTicket/test/index.test.tsx
  client/src/components/UI/molecules/artistCard/index.tsx
  client/src/components/UI/molecules/artistListViewModeSelector/index.tsx
  client/src/components/UI/molecules/calendarBody/index.tsx
  client/src/components/UI/molecules/calendarBody/test/index.test.tsx
  client/src/components/UI/molecules/calendarBody/utils.ts
  client/src/components/UI/molecules/scheduleFanUpModal/index.tsx
  client/src/components/UI/molecules/todayTicket/index.tsx
  client/src/components/UI/molecules/todayTicket/test/index.test.tsx
  client/src/components/UI/molecules/userDropDown/index.tsx
  client/src/components/UI/organisms/ArtistInfoForm/index.tsx
  client/src/components/UI/organisms/ArtistScheduleBox/index.tsx
  client/src/components/UI/organisms/ChatContainer/index.tsx
  client/src/components/UI/organisms/FanFeatureBox/index.tsx
  client/src/components/UI/organisms/artists/index.tsx
  client/src/components/UI/organisms/calendar/index.tsx
  client/src/components/UI/organisms/detailTicket/index.tsx
  client/src/components/UI/organisms/header/index.tsx
  client/src/components/UI/organisms/todayTickets/index.tsx
  client/src/components/hoc/withArtistValidation/index.tsx
  client/src/components/hoc/withGetUser/index.tsx
  client/src/components/hoc/withLoginValidation/index.tsx
  client/src/hooks/useCheckArtist.ts
  client/src/hooks/useFanUP.ts
  client/src/hooks/useInput.ts
  client/src/hooks/useLogin.ts
  client/src/hooks/useMyStream.ts
  client/src/pages/Artist/index.tsx
  client/src/pages/FanUP/index.tsx
  client/src/pages/Home/index.tsx
  client/src/pages/Schedule/index.tsx
  client/src/pages/Ticket/index.tsx
  client/src/pages/Tickets/index.tsx
  client/src/services/artist.service.ts
  client/src/services/ticket.service.ts
  client/src/services/user.service.ts
  client/src/store/artist/artist.test.ts
  client/src/store/artist/index.ts
  client/src/store/index.ts
  client/src/store/user/index.ts
  client/src/types/artist.d.ts
  client/src/types/ticket.d.ts
  client/src/types/user.d.ts
Labels: 🎨 프론트엔드, ✨ Feature

#174 Bug: 알림 이벤트 핸들러 버그 수정
  client/src/components/UI/molecules/NotificationItem/index.tsx
  client/src/components/UI/organisms/NotificationContainer/index.tsx
  client/src/components/UI/organisms/header/index.tsx
Labels: 🎨 프론트엔드

#176 Fix 해당 유저가 아티스트인지 여부 확인
  server/gateway/src/common/types/join-room.d.ts
  server/gateway/src/socket/fanup/fanup.service.ts
Labels: 🐞 Hotfix, ⚡ 백엔드

#177 Fix: ticket 단건 조회 시, artist 정보 추가
  server/services/ticket/src/domain/ticket/ticket.service.ts
Labels: enhancement, ⚡ 백엔드

#178 Feat : 해당 방에 존재하는 사람이 아티스트인지 아닌지 여부 확인
  server/gateway/src/api/core/core.controller.ts
  server/gateway/src/api/core/core.service.ts
  server/gateway/src/socket/fanup/fanup.service.ts
Labels: ⚡ 백엔드, ✨ Feature

#180 Feat/#179 FanUP Artist Validation
  client/src/components/UI/atoms/FanUpJoinBtn/index.tsx
  client/src/components/UI/atoms/FanUpJoinBtn/test/index.test.tsx
  client/src/components/UI/atoms/FeatureModeSelector/index.tsx
  client/src/components/UI/atoms/RoomBtn/index.tsx
  client/src/components/UI/atoms/RoomBtn/test/index.test.tsx
  client/src/components/UI/molecules/SmallTicket/index.tsx
  client/src/components/UI/organisms/ArtistScheduleBox/index.tsx
  client/src/components/UI/organisms/FanFeatureBox/index.tsx
  client/src/components/UI/organisms/RoomList/index.tsx
  client/src/components/UI/organisms/detailTicket/index.tsx
  client/src/components/UI/organisms/todayTickets/index.tsx
  client/src/hooks/useFanUP.ts
  client/src/services/artist.service.ts
  client/src/services/fanup.service.ts
  client/src/types/fanUp.d.ts
Labels: 🎨 프론트엔드, ✨ Feature

#181 Feat/#165 enhance artist logic
  server/gateway/src/api/auth/auth.controller.ts
  server/gateway/src/api/auth/auth.service.ts
  server/gateway/src/api/auth/dto/update-artist.dto.ts
  server/services/auth/src/domain/artist/artist.controller.ts
  server/services/auth/src/domain/artist/artist.service.ts
  server/services/auth/src/domain/artist/dto/request-update-artist.dto.ts
  server/services/ticket/src/domain/ticket/ticket.service.ts
Labels: enhancement, ⚡ 백엔드

#183 Feat/#182 Get Artist Subscribers
  client/src/components/UI/atoms/Participants/index.tsx
  client/src/components/UI/atoms/Video/index.tsx
  client/src/components/UI/molecules/SubscribedUser/index.tsx
  client/src/components/UI/organisms/SubscribedUsers/index.tsx
  client/src/services/artist.service.ts
Labels: 🎨 프론트엔드, ✨ Feature

#185 Feat/#165 구독자 업데이트 시, ticket service와 동기화 로직 추가
  server/services/auth/src/domain/artist/artist.service.ts
  server/services/ticket/src/domain/artist/artist.controller.ts
  server/services/ticket/src/domain/artist/artist.service.ts
Labels: enhancement, ⚡ 백엔드

#184 HotFix: Howling
  client/src/components/UI/atoms/FanUpJoinBtn/index.tsx
  client/src/components/UI/atoms/Video/index.tsx
  client/src/components/UI/organisms/VideoList/index.tsx
Labels: 🎨 프론트엔드, ✨ Feature

#186 Fix 알림 서비스통합
  server/gateway/src/socket/notification/notification.gateway.ts
  server/services/ticket/src/job/job.listener.ts
Labels: 🐞 Hotfix, ⚡ 백엔드

#189 Fix : data 가 없는 경우 체크
  server/gateway/src/socket/fanup/fanup.service.ts
  server/services/core/src/common/constants/res-message.ts
  server/services/core/src/domain/fanup/controller/fanup.controller.ts
Labels: 🐞 Hotfix, ⚡ 백엔드

#190 Hotfix: artist 생성, 수정 반환값 변경 / 오늘 마감 ticket 쿼리 수정
  server/services/auth/src/domain/artist/artist.controller.ts
  server/services/auth/src/domain/artist/artist.service.ts
  server/services/ticket/src/domain/ticket/ticket.service.ts
Labels: 🐞 Hotfix

#193 Fix/#192 UI 깨짐 현상 수정
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/atoms/FanUpJoinBtn/index.tsx
  client/src/components/UI/atoms/SubscribeBtn/index.tsx
  client/src/components/UI/atoms/TicketBarCode/index.tsx
  client/src/components/UI/molecules/HeaderUser/index.tsx
  client/src/components/UI/molecules/SmallTicket/index.tsx
  client/src/components/UI/molecules/allTicket/index.tsx
  client/src/components/UI/molecules/artistCard/index.tsx
  client/src/components/UI/molecules/todayTicket/index.tsx
  client/src/components/UI/organisms/ArtistScheduleBox/index.tsx
  client/src/components/UI/organisms/FanFeatureBox/index.tsx
  client/src/components/UI/organisms/VideoList/index.tsx
  client/src/components/UI/organisms/detailTicket/index.tsx
  client/src/components/UI/organisms/todayTickets/index.tsx
Labels: enhancement, 🎨 프론트엔드

#195 Fix/#194 Anonymous 사용자 티켓팅
  client/src/components/UI/organisms/detailTicket/index.tsx
  client/src/pages/Ticket/index.tsx
Labels: 🐞 Hotfix, 🎨 프론트엔드

#197 Test : Notification Gateway 테스트 제작
  .github/workflows/SERVER-DEPLOY.yml
  server/gateway/package.json
  server/gateway/src/socket/notification/notification.e2e-spec.ts
Labels: 테스트

#199 [Test] FanUP Gateway Test Case 추가
  server/gateway/package.json
  server/gateway/src/socket/fanup/fanup.e2e-spec.ts
  server/gateway/src/socket/fanup/fanup.gateway.ts
  server/gateway/src/socket/notification/notification.e2e-spec.ts
  server/gateway/test/fanup.e2e-spec.ts
Labels: 테스트

#203 Authservice in Gateway 테스트코드 작성
  coverage/lcov.info
  server/gateway/src/api/auth/auth.controller.ts
  server/gateway/src/api/auth/auth.service.spec.ts
  server/gateway/src/api/auth/auth.service.ts
  server/gateway/src/socket/notification/notification.e2e-spec.ts
Labels: 테스트

#205 Test : Core Server Test 세팅
  coverage/lcov.info
  package.json
  server/services/core/package.json
  server/services/core/src/domain/chat/chat.module.ts
  server/services/core/src/domain/chat/controller/chat.controller.spec.ts
  server/services/core/src/domain/chat/service/chat.service.spec.ts
  server/services/core/src/domain/chat/service/chat.service.ts
  server/services/core/src/domain/fanup/controller/fanup.controller.spec.ts
  server/services/core/src/domain/fanup/service/fanup.service.spec.ts
  server/services/core/src/domain/notification/notification.module.ts
  server/services/core/src/domain/notification/service/notification.service.spec.ts
  server/services/core/src/provider/file/controller/file.controller.spec.ts
  server/services/core/src/provider/file/service/file.service.spec.ts
Labels: 🍀 테스트

#207 Test : core chatservice 테스트 코드 작성
  coverage/lcov.info
  package.json
  server/services/core/src/domain/chat/service/chat.service.spec.ts
  server/services/core/src/domain/chat/service/chat.service.ts
Labels: 🍀 테스트

#209 Test case
  coverage/lcov.info
  package.json
  server/services/core/src/domain/chat/service/chat.service.spec.ts
  server/services/core/src/domain/fanup/service/fanup.service.spec.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
Labels: 🍀 테스트

#211 Test/#210 : FanUPService in Core Server 완성
  coverage/lcov.info
  package.json
  server/services/core/src/common/constants/res-message.ts
  server/services/core/src/common/exception/index.ts
  server/services/core/src/common/exception/rpc/fanup-create.exception.ts
  server/services/core/src/domain/fanup/service/fanup.service.spec.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/core/src/provider/file/service/file.service.spec.ts
Labels: 🍀 테스트

#213 [Test] Notification Service in Core Server 테스트 완성
  coverage/lcov.info
  server/services/core/src/domain/notification/service/notification.service.spec.ts
  server/services/core/src/domain/notification/service/notification.service.ts
Labels: 🍀 테스트

#215 [Test] ArtistService in Ticket Server Test 완성
  package.json
  server/services/ticket/src/domain/artist/artist.module.ts
  server/services/ticket/src/domain/artist/artist.service.spec.ts
  server/services/ticket/src/domain/artist/artist.service.ts
Labels: 🍀 테스트

#217 [Test] UserTicketService in Ticket Server Test 완성
  README.md
  server/services/ticket/src/domain/artist/artist.service.spec.ts
  server/services/ticket/src/domain/user-ticket/dto/create-user-ticket.dto.ts
  server/services/ticket/src/domain/user-ticket/user-ticket.module.ts
  server/services/ticket/src/domain/user-ticket/user-ticket.service.spec.ts
  server/services/ticket/src/domain/user-ticket/user-ticket.service.ts
Labels: 🍀 테스트

#219 [Test] TicketService in Ticket Server Test 완성
  coverage/lcov.info
  package.json
  server/gateway/src/api/core/core.service.spec.ts
  server/services/ticket/src/domain/ticket/ticket.module.ts
  server/services/ticket/src/domain/ticket/ticket.service.spec.ts
Labels: 🍀 테스트
