Repository boostcampwm-2022/web03-FanUP, pull requests merged in 2022-11, with the labels that each got.

#11 Feat/#8 GitHub CI 설정
  .github/workflows/SERVER-COVERAGE.yml
  .github/workflows/SERVER-FORMAT.yml
  .gitignore
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/README.md
  server/gateway/package-lock.json
  server/gateway/package.json
  server/services/api/.eslintrc.js
  server/services/api/.gitignore
  server/services/api/.prettierrc
  server/services/api/README.md
  server/services/api/package-lock.json
  server/services/api/package.json
  server/services/auth/.eslintrc.js
  server/services/auth/.gitignore
  server/services/auth/.prettierrc
  server/services/auth/README.md
  server/services/auth/package-lock.json
  server/services/auth/package.json
  server/services/ticket/.eslintrc.js
  server/services/ticket/.gitignore
  server/services/ticket/.prettierrc
  server/services/ticket/README.md
  server/services/ticket/package-lock.json
  server/services/ticket/package.json
Labels: backend

#12 Client 프로젝트 설정
  client/.eslintrc.json
  client/.prettierrc.json
  client/config-overrides.js
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/style/GlobalStyle.tsx
  client/src/style/styled.d.ts
  client/src/style/theme.ts
  client/tsconfig.json
Labels: frontend

#15 Feat/#14 프론트엔드 라이브러리 셋업
  client/package.json
  client/public/banner.png
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/Routes.ts
  client/src/components/UI/layout/header/index.tsx
  client/src/components/UI/layout/header/test/index.test.tsx
  client/src/components/icons/alarm/index.tsx
  client/src/components/icons/logo/index.tsx
  client/src/components/icons/search/index.tsx
  client/src/components/icons/user/index.tsx
  client/src/index.tsx
  client/src/mocks/handlers/_index.ts
  client/src/mocks/handlers/artist.ts
  client/src/mocks/server.ts
  client/src/pages/FanUP/index.tsx
  client/src/pages/Home/index.tsx
  client/src/reportWebVitals.ts
  client/src/services/artist/index.ts
  client/src/services/user/index.ts
  client/src/setupTests.ts
  client/src/store/artist/index.ts
  client/src/store/index.ts
  client/src/store/rootReducer.ts
  client/src/store/user/index.ts
  client/src/style/GlobalStyle.tsx
  client/src/types/artist.d.ts
  client/src/types/user.d.ts
  client/src/utils/serverUrl.ts
  client/src/utils/test/renderWithContext.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: 리뷰요청, 🎨 프론트엔드

#16 Chore/#13 Github Actions deploy 작업 진행
  .github/workflows/SERVER-API-COVERAGE.yml
  .github/workflows/SERVER-AUTH-COVERAGE.yml
  .github/workflows/SERVER-DEPLOY.yml
  .github/workflows/SERVER-FORMAT.yml
  .github/workflows/SERVER-TICKET-COVERAGE.yml
  server/docker-compose.yaml
  server/gateway/.dockerignore
  server/gateway/Dockerfile
  server/gateway/src/api/api.module.ts
  server/gateway/src/auth/auth.module.ts
  server/gateway/src/ticket/ticket.module.ts
  server/services/api/.dockerignore
  server/services/api/Dockerfile
  server/services/api/src/main.ts
  server/services/auth/.dockerignore
  server/services/auth/Dockerfile
  server/services/auth/src/main.ts
  server/services/ticket/.dockerignore
  server/services/ticket/Dockerfile
  server/services/ticket/src/main.ts
Labels: ⚡ 백엔드

#17 Feat/#4 로그인 페이지 UI 구현
  client/.eslintrc.json
  client/.gitignore
  client/config-overrides.js
  client/src/App.tsx
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/atoms/Button/index.tsx
  client/src/components/UI/organisms/OAuthContainer/OAuthContainer.tsx
  client/src/components/UI/organisms/OAuthContainer/index.tsx
  client/src/images/login.svg
  client/src/index.css
  client/src/pages/Login.tsx
  client/src/utils/OAuth.ts
  client/tsconfig.json
Labels: 🎨 프론트엔드

#18 Hotfix/#13 Action 프로세스 수정
  .github/workflows/SERVER-DEPLOY.yml
Labels: 🐞 Hotfix, ⚡ 백엔드

#30 Hotfix/#29 : 테스트 커버리지 수정
  .coveralls.yml
  .github/workflows/.DS_Store
  .github/workflows/CODE-FORMAT.yml
  .github/workflows/SERVER-API-COVERAGE.yml
  .github/workflows/SERVER-TICKET-COVERAGE.yml
  .github/workflows/TEST-COVERAGE.yml
  .gitignore
  babel.config.js
  client/package.json
  package.json
  server/.eslintrc.js
  server/services/api/package-lock.json
  server/services/api/package.json
  server/services/auth/.coveralls.yml
  server/services/auth/package-lock.json
  server/services/auth/package.json
  server/services/auth/src/strategies/jwt.strategy.ts
  server/services/auth/test/app.e2e-spec.ts
  server/services/auth/test/temp.ts
  server/services/ticket/.coveralls.yml
  server/services/ticket/package-lock.json
  server/services/ticket/package.json
  tsconfig.build.json
  tsconfig.json
Labels: 🐞 Hotfix, ⚡ 백엔드

#32 Feat/#31 msa basic setting
  server/.gitignore
  server/gateway/src/api/api.controller.ts
  server/gateway/src/auth/auth.controller.ts
  server/gateway/src/auth/auth.module.ts
  server/gateway/src/auth/auth.service.ts
  server/gateway/src/auth/auth.services.ts
  server/gateway/src/main.ts
  server/gateway/src/ticket/ticket.controller.ts
  server/services/api/src/app.controller.ts
  server/services/api/src/app.service.ts
  server/services/api/src/main.ts
  server/services/auth/src/app.controller.spec.ts
  server/services/auth/src/app.controller.ts
  server/services/auth/src/app.module.ts
  server/services/auth/src/app.service.ts
  server/services/auth/src/auth/auth.controller.ts
  server/services/auth/src/auth/auth.module.ts
  server/services/auth/src/auth/auth.service.ts
  server/services/auth/src/auth/strategies/jwt.strategy.ts
  server/services/auth/src/auth/strategies/refresh.strategy.ts
  server/services/auth/src/main.ts
  server/services/auth/src/prisma/prisma.service.ts
  server/services/ticket/src/app.controller.ts
  server/services/ticket/src/app.service.ts
  server/services/ticket/src/main.ts
Labels: ⚡ 백엔드

#28 Feat/#24 Client Media Stream Connect + WebRTC p2p연결
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UI/atoms/FanUP/CameraBtn/index.tsx
  client/src/components/UI/atoms/FanUP/FeatureModeSelector/index.tsx
  client/src/components/UI/atoms/FanUP/MuteBtn/index.tsx
  client/src/components/UI/atoms/FanUP/MuteBtn/test/index.test.tsx
  client/src/components/UI/atoms/FanUP/Video/index.tsx
  client/src/components/UI/layout/header/index.tsx
  client/src/components/UI/layout/header/test/index.test.tsx
  client/src/components/UI/organisms/FanUP/BottomOptionBar/index.tsx
  client/src/components/UI/organisms/FanUP/BottomOptionBar/test/index.test.tsx
  client/src/components/UI/organisms/FanUP/VideoList/index.tsx
  client/src/hooks/useMyStream.ts
  client/src/hooks/usePreventLeave.ts
  client/src/hooks/useSocket.ts
  client/src/hooks/useWebRTC.ts
  client/src/index.tsx
  client/src/pages/FanUP/index.tsx
  client/src/pages/FanUP/test/index.test.tsx
  client/src/pages/Home/index.tsx
  client/src/store/index.ts
  client/src/store/user/index.ts
  client/src/store/user/user.test.tsx
  client/src/types/user.d.ts
  client/src/utils/test/mockFn.ts
  client/yarn.lock
Labels: 🎨 프론트엔드, ✨ Feature

#42 Feat/#5 클라이언트 로그인 테스트
  client/.eslintrc.json
  client/config-overrides.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/UI/atoms/Loading/index.tsx
  client/src/components/UI/organisms/OAuthContainer/OAuthContainer.tsx
  client/src/components/icons/fish/index.tsx
  client/src/pages/AuthCallback/index.tsx
  client/src/store/user/index.ts
  client/src/types/user.d.ts
  client/src/utils/OAuth.ts
  client/tsconfig.json
  client/yarn.lock
Labels: 🎨 프론트엔드

#39 Feat/#20 fanup socket
  .github/workflows/CODE-FORMAT.yml
  .github/workflows/SERVER-DEPLOY.yml
  .github/workflows/TEST-COVERAGE.yml
  .gitignore
  babel.config.js
  client/package.json
  client/src/components/UI/atoms/FanUP/CameraBtn/test/index.test.tsx
  client/src/components/UI/atoms/FanUP/ExitBtn/test/index.test.tsx
  client/src/components/UI/atoms/FanUP/FeatureModeSelector/test/index.test.tsx
  client/src/components/UI/atoms/FanUP/MuteBtn/test/index.test.tsx
  client/src/components/UI/atoms/FanUP/Participants/test/index.test.tsx
  client/src/components/UI/atoms/FanUP/RoomBtn/test/index.test.tsx
  client/src/components/UI/layout/header/test/index.test.tsx
  client/src/components/UI/organisms/FanUP/BottomOptionBar/test/index.test.tsx
  client/src/components/UI/organisms/FanUP/FeatureBox/test/index.test.tsx
  client/src/components/UI/organisms/FanUP/RoomList/test/index.test.tsx
  client/src/components/UI/organisms/FanUP/chatBox/test/index.test.tsx
  client/src/components/UI/organisms/FanUP/participantsList/test/index.test.tsx
  client/src/pages/FanUP/test/index.test.tsx
  client/src/store/user/index.ts
  client/src/store/user/user.test.tsx
  coverage/lcov.info
  jest.setup.js
  package-lock.json
  package.json
  server/gateway/package-lock.json
  server/gateway/package.json
  server/gateway/src/app.module.ts
  server/gateway/src/core/core.controller.ts
  server/gateway/src/core/core.module.ts
  server/gateway/src/core/core.service.ts
  server/gateway/src/socket/fanup.gateway.ts
  server/gateway/src/socket/socket.module.ts
  server/gateway/test/socket/fanup.e2e-spec.ts
  server/services/core/package.json
  tsconfig.json
Labels: 리뷰요청, ⚡ 백엔드, ✨ Feature

#48 Feat/#47 chatting server
  .github/workflows/CODE-FORMAT.yml
  .github/workflows/SERVER-DEPLOY.yml
  .github/workflows/TEST-COVERAGE.yml
  coverage/lcov.info
  server/gateway/src/main.ts
  server/gateway/src/socket/chat.gateway.ts
  server/gateway/src/socket/socket.module.ts
  server/gateway/src/types/chat.gateway.d.ts
  server/gateway/test/socket/chat.e2e-spec.ts
Labels: 리뷰요청, ⚡ 백엔드, ✨ Feature

#40 Feat/#36 채팅 UI 구현
  client/.eslintrc.json
  client/config-overrides.js
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/atoms/Chat/index.tsx
  client/src/components/UI/atoms/FanUP/chat/index.tsx
  client/src/components/UI/atoms/FanUP/chatForm/index.tsx
  client/src/components/UI/molecules/ChatList/index.tsx
  client/src/components/UI/molecules/InputForm/index.tsx
  client/src/components/UI/organisms/ChatContainer/index.tsx
  client/src/components/UI/organisms/ChatContainer/test/index.test.tsx
  client/src/components/UI/organisms/FanUP/FeatureBox/index.tsx
  client/src/components/UI/organisms/OAuthContainer/OAuthContainer.tsx
  client/src/components/UI/organisms/RoomList/index.tsx
  client/src/components/UI/organisms/RoomList/test/index.test.tsx
  client/src/components/UI/organisms/participantsList/index.tsx
  client/src/components/UI/organisms/participantsList/test/index.test.tsx
  client/src/components/icons/clock/index.tsx
  client/src/components/icons/participants/index.tsx
  client/src/components/icons/send/index.tsx
  client/tsconfig.json
Labels: 리뷰요청, 🎨 프론트엔드

#58 Feat/#57 file upload
  coverage/lcov.info
  server/gateway/package-lock.json
  server/gateway/package.json
  server/gateway/src/core/core.controller.ts
  server/gateway/src/core/core.service.ts
  server/services/core/src/app.module.ts
  server/services/core/src/main.ts
  server/services/core/src/provider/file/controller/file.controller.ts
  server/services/core/src/provider/file/service/file.service.ts
Labels: ⚡ 백엔드, ✨ Feature

#60 Feat/#59 fanup logic
  coverage/lcov.info
  server/gateway/src/app.module.ts
  server/gateway/src/common/middleware/logger.middleware.ts
  server/gateway/src/common/types/chat.gateway.d.ts
  server/gateway/src/common/types/create-chat.d.ts
  server/gateway/src/common/types/custom.response.d.ts
  server/gateway/src/common/types/index.ts
  server/gateway/src/common/types/join-room.d.ts
  server/gateway/src/common/types/join-socket-room.ts
  server/gateway/src/common/types/send-message.ts
  server/gateway/src/common/types/socket-chat.d.ts
  server/gateway/src/common/types/validate-user.d.ts
  server/gateway/src/core/core.service.ts
  server/gateway/src/socket/chat.gateway.ts
  server/gateway/src/socket/fanup/fanup.gateway.ts
  server/gateway/src/socket/fanup/fanup.service.ts
  server/gateway/src/socket/socket.module.ts
  server/gateway/src/types/index.ts
  server/gateway/test/fanup.e2e-spec.ts
  server/gateway/test/socket/fanup.e2e-spec.ts
  server/services/core/README.md
  server/services/core/prisma/schema.prisma
  server/services/core/src/app.controller.ts
  server/services/core/src/common/constants/res-message.ts
  server/services/core/src/common/exception/chat-create-fail.exception.ts
  server/services/core/src/common/exception/chat-not-found.exception.ts
  server/services/core/src/common/exception/chatroom-not-found.exception.ts
  server/services/core/src/common/exception/custom-rpc.exception.ts
  server/services/core/src/common/exception/http/file-bad-request.exception.ts
  server/services/core/src/common/exception/index.ts
  server/services/core/src/common/exception/rpc/chat-create-fail.exception.ts
  server/services/core/src/common/exception/rpc/chat-not-found.exception.ts
  server/services/core/src/common/exception/rpc/chatroom-not-found.exception.ts
  server/services/core/src/common/exception/rpc/fanup-not-found.exception.ts
  server/services/core/src/common/exception/rpc/fanup-update.exception.ts
  server/services/core/src/common/filter/index.ts
  server/services/core/src/common/filter/rpc-exception.filter.ts
  server/services/core/src/common/interceptor/transform.interceptor.ts
  server/services/core/src/domain/chat/service/chat.service.ts
  server/services/core/src/domain/fanup/controller/fanup.controller.ts
  server/services/core/src/domain/fanup/dto/create-fanup.dto.ts
  server/services/core/src/domain/fanup/dto/create-time.dto.ts
  server/services/core/src/domain/fanup/dto/index.ts
  server/services/core/src/domain/fanup/dto/update-fanup.dto.ts
  server/services/core/src/domain/fanup/dto/update-time.dto.ts
  server/services/core/src/domain/fanup/fanup.module.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/core/src/provider/file/service/file.service.ts
Labels: ⚡ 백엔드, ✨ Feature

#65 Feat/#64 렌더링 최적화
  client/public/index.html
  client/public/manifest.json
  client/src/components/UI/atoms/CameraBtn/index.tsx
  client/src/components/UI/atoms/FeatureModeSelector/index.tsx
  client/src/components/UI/atoms/LazyImg/index.tsx
  client/src/components/UI/atoms/MuteBtn/index.tsx
  client/src/components/UI/atoms/calendarNextBtn/index.tsx
  client/src/components/UI/atoms/calendarPrevBtn/index.tsx
  client/src/components/UI/molecules/artistCard/index.tsx
  client/src/components/UI/molecules/artistCard/test/index.test.tsx
  client/src/components/UI/molecules/artistListViewModeSelector/index.tsx
  client/src/components/UI/molecules/calendarBody/index.tsx
  client/src/components/UI/molecules/calendarHeader/index.tsx
  client/src/components/UI/molecules/scheduleFanUpModal/index.tsx
  client/src/components/UI/organisms/FeatureBox/index.tsx
  client/src/components/UI/organisms/VideoList/index.tsx
  client/src/components/UI/organisms/artists/index.tsx
  client/src/components/UI/organisms/artists/test/index.test.tsx
  client/src/components/UI/organisms/artistsBox/index.tsx
  client/src/components/UI/organisms/artistsBox/test/index.test.tsx
  client/src/components/UI/organisms/calendar/index.tsx
  client/src/hooks/useWebRTC.ts
  client/src/pages/Home/index.tsx
  client/src/pages/Home/test/index.test.tsx
  client/src/types/artist.d.ts
  client/src/utils/dummy.ts
  client/src/utils/test/mockFn.ts
Labels: 리뷰요청, 🎨 프론트엔드, ✨ Feature

#67 Feat/#66 fanup schedule
  server/README.md
  server/services/core/package-lock.json
  server/services/core/package.json
  server/services/core/src/app.module.ts
  server/services/core/src/common/constants/index.ts
  server/services/core/src/common/constants/microservices.ts
  server/services/core/src/common/type/basic-date.d.ts
  server/services/core/src/common/type/index.ts
  server/services/core/src/common/util/date.ts
  server/services/core/src/common/util/index.ts
  server/services/core/src/domain/fanup/service/fanup.service.ts
  server/services/core/src/job/job.module.ts
  server/services/core/src/job/task/basic.task.ts
Labels: 리뷰요청, ⚡ 백엔드, ✨ Feature

#69 Feat/#68 client github actions
  .github/workflows/CLIENT_DEPLOY.yml
  client/deploy.sh
Labels: 🎨 프론트엔드

#82 Feat/#41 스트리밍-채팅 소켓 통일
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/UI/organisms/ChatContainer/index.tsx
  client/src/hooks/useFanUP.ts
  client/src/hooks/useSocket.ts
  client/src/pages/FanUP/index.tsx
  client/src/socket.ts
Labels: 🎨 프론트엔드

#83 Feat 로그인 로직, 배포 서버 도메인 연결
  client/src/components/UI/organisms/OAuthContainer/OAuthContainer.tsx
  client/src/utils/OAuth.ts
Labels: 🎨 프론트엔드
